version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: root
      MYSQL_USER: root
      MYSQL_PASSWORD: Baba@1234
      MYSQL_ROOT_PASSWORD: Baba@1234
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      MYSQL_DATABASE: root
      MYSQL_USER: root
      MYSQL_PASSWORD: Baba@1234
      MYSQL_HOST: db
      MYSQL_PORT: 3306

volumes:
  mysql_data: